import crypto from 'crypto';
import { Project, SyntaxKind } from 'ts-morph';

/**
 * VerifierNode - Verifies code generated by ExecutorNode using AST
 *
 * @param {import('../state.js').GraphState} state
 * @returns {Partial<import('../state.js').GraphState>}
 */
export async function verifierNode(state) {
  const { generatedCode, currentFile } = state;

  if (!generatedCode) {
    console.warn('⚠️  [VerifierNode] No code to verify');
    return { errors: ['No code generated'] };
  }

  const filePath =
    currentFile?.relativeToProject || currentFile?.filePath || 'unknown.tsx';
  console.log(`\n🔍 [VerifierNode] Verifying: ${filePath}`);

  const errors = [];

  const project = new Project({
    useInMemoryFileSystem: true,
    skipFileDependencyResolution: true,
    compilerOptions: {
      allowJs: true,
      jsx: 2,
      noResolve: true,
      isolatedModules: true,
    },
  });

  const sourceFile = project.createSourceFile(
    `temp_verify.tsx`,
    generatedCode,
    { overwrite: true }
  );
  try {
    // 1. فحص الـ Syntax الأساسي
    const diagnostics = project
      .getProgram()
      .getSyntacticDiagnostics(sourceFile);
    for (const diag of diagnostics) {
      const message =
        typeof diag.getMessageText() === 'string'
          ? diag.getMessageText()
          : diag.getMessageText().getMessageText();
      errors.push(
        `[TS${diag.getCode()}] Line ${diag.getLineNumber()}: ${message}`
      );
    }

    // 🔥 التعديل الجوهري: لا تقم بفحص الـ AST بحثاً عن (div) وغيرها
    // إلا إذا كان الكود سليماً تماماً من ناحية الـ Syntax
    if (errors.length === 0) {
      const astErrors = analyzeASTForErrors(sourceFile, filePath);
      errors.push(...astErrors);
    }
  } catch (error) {
    console.warn('⚠️ [VerifierNode] ts-morph crashed:', error.message);
    errors.push(`Critical Syntax Error: Could not parse file.`);
  }

  if (errors.length === 0) {
    console.log(`✅ [VerifierNode] Code is valid`);
  } else {
    console.log(`❌ [VerifierNode] Found ${errors.length} errors:`);
    errors.slice(0, 3).forEach((e) => console.log(`   - ${e}`));
  }

  const errorHash =
    errors.length > 0
      ? crypto
          .createHash('md5')
          .update(errors.join(''))
          .digest('hex')
          .slice(0, 16)
      : null;

  return {
    errors,
    lastErrorHash: errorHash,
  };
}

/**
 * Analyzes the AST for specific web-only patterns or HTML elements
 * @param {import('ts-morph').SourceFile} sourceFile
 * @param {string} filePath
 */
function analyzeASTForErrors(sourceFile, filePath) {
  const errors = [];
  const isComponent =
    /\.(tsx|jsx)$/i.test(filePath) || sourceFile.getText().includes('react');

  if (isComponent) {
    const jsxElements = sourceFile.getDescendantsOfKind(SyntaxKind.JsxElement);
    const jsxSelfClosing = sourceFile.getDescendantsOfKind(
      SyntaxKind.JsxSelfClosingElement
    );

    const checkTagName = (tagName, line) => {
      const lowerTag = tagName.toLowerCase();
      if (lowerTag === 'div')
        errors.push(
          `Line ${line}: Using HTML <div> instead of React Native <View>`
        );
      if (lowerTag === 'span')
        errors.push(
          `Line ${line}: Using HTML <span> instead of React Native <Text>`
        );
      if (lowerTag === 'img')
        errors.push(
          `Line ${line}: Using HTML <img> instead of React Native <Image>`
        );
      if (lowerTag === 'p')
        errors.push(
          `Line ${line}: Using HTML <p> instead of React Native <Text>`
        );
      if (lowerTag === 'button')
        errors.push(
          `Line ${line}: Using HTML <button> instead of React Native <TouchableOpacity> or <Pressable>`
        );
      if (lowerTag === 'input')
        errors.push(
          `Line ${line}: Using HTML <input> instead of React Native <TextInput>`
        );
    };

    jsxElements.forEach((element) => {
      const openingElement = element.getOpeningElement();
      const tagName = openingElement.getTagNameNode().getText();
      checkTagName(tagName, openingElement.getStartLineNumber());
    });

    jsxSelfClosing.forEach((element) => {
      const tagName = element.getTagNameNode().getText();
      checkTagName(tagName, element.getStartLineNumber());
    });
  }

  const identifiers = sourceFile.getDescendantsOfKind(SyntaxKind.Identifier);
  const webAPIs = ['document', 'window', 'localStorage', 'sessionStorage'];

  identifiers.forEach((id) => {
    const text = id.getText();
    if (webAPIs.includes(text)) {
      const parent = id.getParent();

      // 🔥 تم إصلاح المقارنة هنا: نقارن الـ Text بدلاً من الكائنات نفسها
      if (
        parent &&
        parent.getKind() === SyntaxKind.PropertyAccessExpression &&
        parent.getExpression().getText() === text
      ) {
        errors.push(
          `Line ${id.getStartLineNumber()}: Web-only API detected: ${text}.${parent.getName()}`
        );
      } else if (
        parent &&
        parent.getKind() !== SyntaxKind.VariableDeclaration &&
        parent.getKind() !== SyntaxKind.PropertyAssignment
      ) {
        errors.push(
          `Line ${id.getStartLineNumber()}: Web-only API detected: ${text}`
        );
      }
    }
  });

  return [...new Set(errors)];
}
