import crypto from 'crypto';
import path from 'path';
import { Project, SyntaxKind } from 'ts-morph';

/**
 * VerifierNode - Verifies code generated by ExecutorNode using AST and TS Compiler
 *
 * @param {import('../state.js').GraphState} state
 * @returns {Partial<import('../state.js').GraphState>}
 */
export async function verifierNode(state) {
  const { generatedCode, currentFile } = state;

  if (!generatedCode) {
    console.warn('⚠️  [VerifierNode] No code to verify');
    return { errors: ['No code generated'] };
  }

  const filePath =
    currentFile?.relativeToProject || currentFile?.filePath || 'unknown.tsx';
  console.log(`\n🔍 [VerifierNode] Verifying: ${filePath}`);

  const errors = [];
  const missingPkgs = [];

  // Initialize isolated compiler environment without DOM libraries
  const project = new Project({
    compilerOptions: {
      allowJs: true,
      jsx: 2, // React
      moduleResolution: 2, // Node
      baseUrl: state.rnProjectPath || process.cwd(),
      skipLibCheck: true,
      esModuleInterop: true,
    },
  });

  const originalPath =
    currentFile?.relativeToProject || `temp_${Date.now()}.tsx`;
  const targetPath = state.pathMap?.[originalPath] || originalPath;

  const tempFilePath = path.join(
    state.rnProjectPath || process.cwd(),
    targetPath
  );

  const sourceFile = project.createSourceFile(tempFilePath, generatedCode, {
    overwrite: true,
  });

  try {
    const diagnostics = sourceFile.getPreEmitDiagnostics();
    const logicErrors = [];
    const currentAttempts = state.installAttempts || 0;

    diagnostics.forEach((diag) => {
      const code = diag.getCode();
      const messageObj = diag.getMessageText();
      const message =
        typeof messageObj === 'string'
          ? messageObj
          : messageObj && typeof messageObj.getMessageText === 'function'
            ? messageObj.getMessageText()
            : String(messageObj);

      // Handle missing module errors (TS2307)
      if (code === 2307) {
        const match =
          typeof message === 'string'
            ? message.match(/Cannot find module '([^']+)'/) ||
              message.match(/module '([^']+)'/)
            : null;

        if (match && match[1]) {
          const rawName = match[1];

          // Ignore relative paths entirely to prevent hallucinated module installs
          if (rawName.startsWith('.') || rawName.startsWith('/')) {
            return;
          }

          // Clean library name for Scoped Packages
          const pkgName = rawName.startsWith('@')
            ? rawName.split('/').slice(0, 2).join('/')
            : rawName.split('/')[0];

          // Enforce circuit breaker
          if (currentAttempts < 2) {
            missingPkgs.push(pkgName);
          } else {
            let errorMsg = `[TS${code}] Line ${diag.getLineNumber()}: ${typeof message === 'object' ? JSON.stringify(message) : message}. DO NOT IMPORT THIS MODULE. REMOVE IT.`;
            logicErrors.push(errorMsg);
          }
        }
      } else {
        // Capture all other TS errors (including TS2584 for undefined window/document)
        let errorMsg = `[TS${code}] Line ${diag.getLineNumber()}: ${typeof message === 'object' ? JSON.stringify(message) : message}`;
        logicErrors.push(errorMsg);
      }
    });

    errors.push(...logicErrors);

    // Only run AST HTML check if the file passes TypeScript semantic checks
    if (errors.length === 0) {
      const astErrors = analyzeASTForErrors(
        sourceFile,
        filePath,
        state.pathMap
      );
      errors.push(...astErrors);
    }
  } catch (error) {
    console.warn('⚠️ [VerifierNode] ts-morph crashed:', error.message);
    errors.push(`Critical Syntax Error: Could not parse file.`);
  }

  if (errors.length === 0 && missingPkgs.length === 0) {
    console.log(`✅ [VerifierNode] Code is valid`);
  } else if (missingPkgs.length > 0) {
    console.log(
      `📦 [VerifierNode] Missing modules detected: ${missingPkgs.join(', ')}`
    );
  } else {
    console.log(`❌ [VerifierNode] Found ${errors.length} errors:`);
    errors.slice(0, 3).forEach((e) => console.log(`   - ${e}`));
  }

  const errorHash =
    errors.length > 0
      ? crypto
          .createHash('md5')
          .update(errors.join(''))
          .digest('hex')
          .slice(0, 16)
      : null;

  return {
    errors,
    missingDependencies: [...new Set(missingPkgs)],
    lastErrorHash: errorHash,
  };
}

/**
 * Analyzes the AST using dynamic architectural rules and validates Routes.
 * @param {import('ts-morph').SourceFile} sourceFile
 * @param {string} filePath
 * @param {Object} pathMap
 */
function analyzeASTForErrors(sourceFile, filePath, pathMap = {}) {
  const errors = [];
  const isComponent =
    /\.(tsx|jsx)$/i.test(filePath) || sourceFile.getText().includes('react');

  if (isComponent) {
    const jsxElements = sourceFile.getDescendantsOfKind(SyntaxKind.JsxElement);
    const jsxSelfClosing = sourceFile.getDescendantsOfKind(
      SyntaxKind.JsxSelfClosingElement
    );

    // 1. Check for forbidden web elements
    const checkDynamicTagName = (tagName, line) => {
      if (/^[a-z]/.test(tagName)) {
        errors.push(
          `Line ${line}: Unsupported Web DOM element <${tagName}> detected. You MUST use React Native components (e.g., View, Text, Pressable, etc.).`
        );
      }
    };

    // 2. 🚨 Build a list of Valid Routes from pathMap
    const validRoutes = new Set(
      Object.values(pathMap).map((p) => {
        let route = '/' + p.replace(/^app\//i, '').replace(/\.tsx$/i, '');
        if (route.endsWith('/index')) route = route.replace('/index', '');
        if (route.endsWith('/_layout')) route = route.replace('/_layout', '');
        return route === '' ? '/' : route.toLowerCase();
      })
    );

    // 3. 🚨 Dead Links Validator
    const checkHrefForDeadLinks = (element, line) => {
      const tagName = element.getTagNameNode().getText();
      if (tagName === 'Link' || tagName === 'Redirect') {
        const hrefAttr = element.getAttribute('href');
        if (hrefAttr && hrefAttr.getKind() === SyntaxKind.JsxAttribute) {
          const val = hrefAttr
            .getInitializer()
            ?.getText()
            ?.replace(/['"]/g, '');
          // If the link is static text, not an external link, and doesn't contain dynamic variables
          if (
            val &&
            !val.startsWith('http') &&
            !val.includes('{') &&
            !validRoutes.has(val.toLowerCase())
          ) {
            const available = Array.from(validRoutes).join(', ');
            errors.push(
              `Line ${line}: CRITICAL ROUTING ERROR. Dead link detected. The route "${val}" DOES NOT EXIST. Valid Expo routes are: [${available}]. You MUST update the 'href' to one of the valid routes or fallback to "/".`
            );
          }
        }
      }
    };

    jsxElements.forEach((element) => {
      const openingElement = element.getOpeningElement();
      const tagName = openingElement.getTagNameNode().getText().split('.')[0];
      checkDynamicTagName(tagName, openingElement.getStartLineNumber());
      checkHrefForDeadLinks(
        openingElement,
        openingElement.getStartLineNumber()
      );
    });

    jsxSelfClosing.forEach((element) => {
      const tagName = element.getTagNameNode().getText().split('.')[0];
      checkDynamicTagName(tagName, element.getStartLineNumber());
      checkHrefForDeadLinks(element, element.getStartLineNumber());
    });
  }

  return [...new Set(errors)];
}
