import crypto from 'crypto';
import path from 'path';
import { Project, SyntaxKind } from 'ts-morph';

/**
 * VerifierNode - Verifies code generated by ExecutorNode using AST
 *
 * @param {import('../state.js').GraphState} state
 * @returns {Partial<import('../state.js').GraphState>}
 */
export async function verifierNode(state) {
  const { generatedCode, currentFile } = state;

  if (!generatedCode) {
    console.warn('⚠️  [VerifierNode] No code to verify');
    return { errors: ['No code generated'] };
  }

  const filePath =
    currentFile?.relativeToProject || currentFile?.filePath || 'unknown.tsx';
  console.log(`\n🔍 [VerifierNode] Verifying: ${filePath}`);

  const errors = [];
  const missingPkgs = [];

  const project = new Project({
    compilerOptions: {
      allowJs: true,
      jsx: 2, // React
      moduleResolution: 2, // Node
      baseUrl: state.rnProjectPath || process.cwd(),
      skipLibCheck: true,
    },
  });

  const originalPath =
    currentFile?.relativeToProject || `temp_${Date.now()}.tsx`;
  // Use the new path if it exists in pathMap, otherwise use the original path
  const targetPath = state.pathMap?.[originalPath] || originalPath;

  const tempFilePath = path.join(
    state.rnProjectPath || process.cwd(),
    targetPath
  );
  const sourceFile = project.createSourceFile(tempFilePath, generatedCode, {
    overwrite: true,
  });
  try {
    // 1. Get Pre Emit Diagnostics to capture both Syntax and Semantic errors (like missing modules)
    const diagnostics = sourceFile.getPreEmitDiagnostics();
    const logicErrors = [];
    const currentAttempts = state.installAttempts || 0;

    diagnostics.forEach((diag) => {
      const code = diag.getCode();
      const messageObj = diag.getMessageText();
      const message =
        typeof messageObj === 'string'
          ? messageObj
          : messageObj && typeof messageObj.getMessageText === 'function'
            ? messageObj.getMessageText()
            : String(messageObj);

      // Architectural condition: if the error is a missing library, and we haven't exceeded two attempts
      if (code === 2307 && currentAttempts < 2) {
        const match =
          typeof message === 'string'
            ? message.match(/Cannot find module '([^']+)'/) ||
              message.match(/module '([^']+)'/)
            : null;
        if (match && match[1]) {
          const rawName = match[1];

          // Completely ignore relative paths (Local Imports)
          if (rawName.startsWith('.') || rawName.startsWith('/')) return;

          // Clean library name (support Scoped Packages)
          const pkgName = rawName.startsWith('@')
            ? rawName.split('/').slice(0, 2).join('/')
            : rawName.split('/')[0];

          missingPkgs.push(pkgName);
        }
      } else {
        // Any other error, or if we exceeded attempts, send it as a logic error to Healer for AI to solve
        let errorMsg = `[TS${code}] Line ${diag.getLineNumber()}: ${typeof message === 'object' ? JSON.stringify(message) : message}`;
        logicErrors.push(errorMsg);
      }
    });

    errors.push(...logicErrors);

    // 🔥 Fundamental change: Do not scan AST for (div) etc.
    // Unless the code is completely sound syntactically
    if (errors.length === 0) {
      const astErrors = analyzeASTForErrors(sourceFile, filePath);
      errors.push(...astErrors);
    }
  } catch (error) {
    console.warn('⚠️ [VerifierNode] ts-morph crashed:', error.message);
    errors.push(`Critical Syntax Error: Could not parse file.`);
  }

  if (errors.length === 0) {
    console.log(`✅ [VerifierNode] Code is valid`);
  } else {
    console.log(`❌ [VerifierNode] Found ${errors.length} errors:`);
    errors.slice(0, 3).forEach((e) => console.log(`   - ${e}`));
  }

  const errorHash =
    errors.length > 0
      ? crypto
          .createHash('md5')
          .update(errors.join(''))
          .digest('hex')
          .slice(0, 16)
      : null;

  return {
    errors,
    missingDependencies: [...new Set(missingPkgs)],
    lastErrorHash: errorHash,
  };
}

/**
 * Analyzes the AST for specific web-only patterns or HTML elements
 * @param {import('ts-morph').SourceFile} sourceFile
 * @param {string} filePath
 */
function analyzeASTForErrors(sourceFile, filePath) {
  const errors = [];
  const isComponent =
    /\.(tsx|jsx)$/i.test(filePath) || sourceFile.getText().includes('react');

  if (isComponent) {
    const jsxElements = sourceFile.getDescendantsOfKind(SyntaxKind.JsxElement);
    const jsxSelfClosing = sourceFile.getDescendantsOfKind(
      SyntaxKind.JsxSelfClosingElement
    );

    const checkTagName = (tagName, line) => {
      const lowerTag = tagName.toLowerCase();
      if (lowerTag === 'div')
        errors.push(
          `Line ${line}: Using HTML <div> instead of React Native <View>`
        );
      if (lowerTag === 'span')
        errors.push(
          `Line ${line}: Using HTML <span> instead of React Native <Text>`
        );
      if (lowerTag === 'img')
        errors.push(
          `Line ${line}: Using HTML <img> instead of React Native <Image>`
        );
      if (lowerTag === 'p')
        errors.push(
          `Line ${line}: Using HTML <p> instead of React Native <Text>`
        );
      if (lowerTag === 'button')
        errors.push(
          `Line ${line}: Using HTML <button> instead of React Native <TouchableOpacity> or <Pressable>`
        );
      if (lowerTag === 'input')
        errors.push(
          `Line ${line}: Using HTML <input> instead of React Native <TextInput>`
        );
    };

    jsxElements.forEach((element) => {
      const openingElement = element.getOpeningElement();
      const tagName = openingElement.getTagNameNode().getText();
      checkTagName(tagName, openingElement.getStartLineNumber());
    });

    jsxSelfClosing.forEach((element) => {
      const tagName = element.getTagNameNode().getText();
      checkTagName(tagName, element.getStartLineNumber());
    });
  }

  const identifiers = sourceFile.getDescendantsOfKind(SyntaxKind.Identifier);
  const webAPIs = ['document', 'window', 'localStorage', 'sessionStorage'];

  identifiers.forEach((id) => {
    const text = id.getText();
    if (webAPIs.includes(text)) {
      const parent = id.getParent();

      // 🔥 The comparison was fixed here: compare Text instead of the objects themselves
      if (
        parent &&
        parent.getKind() === SyntaxKind.PropertyAccessExpression &&
        parent.getExpression().getText() === text
      ) {
        errors.push(
          `Line ${id.getStartLineNumber()}: Web-only API detected: ${text}.${parent.getName()}`
        );
      } else if (
        parent &&
        parent.getKind() !== SyntaxKind.VariableDeclaration &&
        parent.getKind() !== SyntaxKind.PropertyAssignment
      ) {
        errors.push(
          `Line ${id.getStartLineNumber()}: Web-only API detected: ${text}`
        );
      }
    }
  });

  return [...new Set(errors)];
}
