import path from 'path';

export class PathMapper {
  /**
   * Calculates the exact new relative import paths for a file based on pathMap.
   * @param {string} currentFilePath - Original path (relative to project)
   * @param {string} currentFileContent - Original file content
   * @param {Object} pathMap - Map of old paths to new paths
   * @returns {Object} { [oldImportString]: newExactImportString }
   */
  static calculateExactImports(currentFilePath, currentFileContent, pathMap) {
    const exactImports = {};
    if (!currentFileContent || !currentFilePath || !pathMap)
      return exactImports;

    // Matches exactly: import ... from './something' or '../something'
    const importRegex = /(?:from|import)\s+['"](\.[^'"]+)['"]/g;
    let match;

    const currentDir = path.dirname(currentFilePath).replace(/\\/g, '/');
    const newCurrentPath = pathMap[currentFilePath] || currentFilePath;
    const newCurrentDir = path.dirname(newCurrentPath).replace(/\\/g, '/');

    while ((match = importRegex.exec(currentFileContent)) !== null) {
      const importString = match[1];

      // 1. Resolve absolute path of the imported file in the original structure
      let importedProjectRelative = path.posix
        .join(currentDir, importString)
        .replace(/\\/g, '/');

      // 2. Find the mapped new path
      let newImportedPath = null;

      if (pathMap[importedProjectRelative]) {
        newImportedPath = pathMap[importedProjectRelative];
      } else {
        // Prefix match for missing extensions
        for (const [oldPath, newPath] of Object.entries(pathMap)) {
          const oldPathBase = oldPath.replace(/\.[^/.]+$/, '');
          if (oldPathBase === importedProjectRelative) {
            newImportedPath = newPath;
            break;
          }
        }
      }

      // 3. Calculate the exact new relative import
      if (newImportedPath) {
        let exactRelative = path.posix.relative(newCurrentDir, newImportedPath);

        // Remove extension from the new import string for clean TS/JS imports
        exactRelative = exactRelative.replace(/\.[^/.]+$/, '');

        // Ensure it starts with "."
        if (!exactRelative.startsWith('.')) {
          exactRelative = './' + exactRelative;
        }

        exactImports[importString] = exactRelative;
      }
    }

    return exactImports;
  }

  /**
   * Generates a map of old paths to new paths based on file role and conventions.
   * Prioritizes precise routes generated by RouteAnalyzer.
   * @param {Array<Object>} files - List of file objects from fileScanner
   * @param {Object} routeMap - Custom overrides generated by AST scanning
   * @returns {Object} { [oldPath]: newPath }
   */
  static generateMap(files, routeMap = {}) {
    const pathMap = {};

    for (const file of files) {
      const oldPath = file.relativeToProject;
      let refinedPath;

      // If RouteAnalyzer found this file to be a routed component/layout, use it exactly
      if (routeMap[oldPath]) {
        refinedPath = routeMap[oldPath];
      } else {
        refinedPath = this.determineNewPath(file);
      }

      // 🚨 [Strict Standard]: Uniform casing for routing paths.
      // Any file located within the app/ folder must be lowercase to avoid routing issues.
      if (refinedPath.startsWith('app/')) {
        refinedPath = refinedPath.toLowerCase();
      }

      pathMap[oldPath] = refinedPath;
    }

    return pathMap;
  }

  /**
   * Determines the new path for a single file.
   * @param {Object} file - fileObject from scanner
   * @returns {string} importable new path
   */
  static determineNewPath(file) {
    let normalizedPath = file.relativeToProject.replace(/\\/g, '/');
    if (normalizedPath.startsWith('src/')) {
      normalizedPath = normalizedPath.substring(4);
    }

    const parts = normalizedPath.split('/');
    const filename = parts[parts.length - 1];
    const basename = path.basename(filename, path.extname(filename));
    const basenameLower = basename.toLowerCase();

    // 1. Root Fallbacks
    if (/^(main|index)\.(js|jsx|ts|tsx)$/.test(normalizedPath)) {
      return `app/_layout.tsx`;
    }
    if (/^App\.(js|jsx|ts|tsx)$/.test(normalizedPath)) {
      return `app/index.tsx`; // Will perform a redirect to /(tabs)/...
    }

    // 2. 🚨 Grouping Layouts inside a Route Group
    if (basenameLower.includes('layout') || basenameLower === 'appshell') {
      return `app/(tabs)/_layout.tsx`;
    }

    // 3. 🚨 Forcing all pages under the same layout/wrapper
    if (
      this.isInFolder(parts, 'pages') ||
      this.isInFolder(parts, 'screens') ||
      this.isInFolder(parts, 'views') ||
      basenameLower.endsWith('screen') ||
      basenameLower.endsWith('page')
    ) {
      return `app/(tabs)/${filename.replace(/\.jsx?$/, '.tsx')}`.toLowerCase();
    }

    // 4. Sub-components
    if (this.isInFolder(parts, 'components')) {
      return `components/${this.cleanPath(parts, ['components'])}`.replace(
        /\.jsx?$/,
        '.tsx'
      );
    }

    // 5. Shared Files (Hooks, Services, Utils)
    if (this.isInFolder(parts, 'hooks'))
      return `hooks/${this.cleanPath(parts, ['hooks'])}`.replace(
        /\.jsx?$/,
        '.ts'
      );
    if (this.isInFolder(parts, 'services') || this.isInFolder(parts, 'api'))
      return `services/${this.cleanPath(parts, ['services', 'api'])}`.replace(
        /\.jsx?$/,
        '.ts'
      );
    if (this.isInFolder(parts, 'utils') || this.isInFolder(parts, 'helpers'))
      return `utils/${this.cleanPath(parts, ['utils', 'helpers'])}`.replace(
        /\.jsx?$/,
        '.ts'
      );
    if (
      this.isInFolder(parts, 'context') ||
      this.isInFolder(parts, 'contexts') ||
      this.isInFolder(parts, 'providers')
    )
      return `context/${this.cleanPath(parts, ['context', 'contexts', 'providers'])}`.replace(
        /\.jsx?$/,
        '.tsx'
      );

    // Assets and Resources
    if (
      this.isInFolder(parts, 'assets') ||
      this.isInFolder(parts, 'images') ||
      this.isInFolder(parts, 'icons')
    ) {
      return `assets/${this.cleanPath(parts, ['assets', 'images', 'icons'])}`;
    }

    // Final Fallback
    return normalizedPath.replace(/\.js$/, '.ts').replace(/\.jsx$/, '.tsx');
  }

  static isInFolder(parts, folderName) {
    return parts.includes(folderName);
  }

  static cleanPath(parts, folderNamesToRemove) {
    const newParts = parts.filter((p) => !folderNamesToRemove.includes(p));
    return newParts.join('/');
  }
}
